package:
  name: "micromet"
  version: "0.2.0"

source:
  git_rev: v0.2.0
  git_url: https://github.com/utah-geological-survey/MicroMet

requirements:
  host:
    - python
    - setuptools
  build:
    - python >=3.9
  run:
    - python >=3.9
    - scipy
    - pandas
    - numpy
    - numba
    - statsmodels
    - metpy
    - jupyter
    - scikit-learn
    - plotly
    - fluxdataqaqc
    - pingouin
    - sqlalchemy

about:
  home: https://github.com/utah-geological-survey/MicroMet
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "Scripts to process raw Eddy Covariance data for estimation of evapotranspiration."

extra:
  recipe-maintainers:
    - inkenbrandt